// Sample file 63
// Linux Window Manager Wine Compatibility
// Contributors: Hemesh Kasukurthy, Rutvij Vinukonda, Taksh Gaikwaid, Vivian Sharmala
R7pNXfy2kdwY14dSTYiWWh0O4qkG4rgpbgaXJ8cPQHGUUkm6PMn7HUYcXx7xWMYrCOp9POL2lGd4KeSZqxSVPOzIduigOVclEJD2RDR5lyKSQyHHi7Wpux4hEEwLbdq31hgKBsmXMvx8DsfVXSIYZQW6d5D9RlxKzWiuNVA39R2xfsRZg8VKrqLoXuQcS1uPUXxdFCZT
